# -*- coding: utf-8 -*-
"""Tugas Personal 8 (Pebryan).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DDBLcAxSPR4L5NtWVLj8nGUY8-3ZCBEH

---

## Deque.py `⤵`
"""

# Mengimpor deque dari module collections
# deque digunakan untuk membuat queue (antrian) yang lebih cepat dibanding list
from collections import deque

# Membuat queue dengan kapasitas maksimal 3 data
customQueue = deque(maxlen=3)

# Menampilkan queue awal (masih kosong)
print(customQueue)

# Menambahkan data ke dalam queue
customQueue.append(1)
customQueue.append(2)
customQueue.append(3)

# Karena maxlen=3, saat menambah data ke-4
# data paling depan (1) akan otomatis terhapus
customQueue.append(4)

# Hasil queue sekarang: deque([2, 3, 4], maxlen=3)
print(customQueue)

# Menghapus seluruh isi queue
# method clear() tidak mengembalikan nilai apapun (None)
print(customQueue.clear())

# Menampilkan queue setelah dikosongkan
print(customQueue)

"""---

### QueueLinkedList.py `⤵`
"""

# Membuat class Node untuk menyimpan data dan alamat node berikutnya
class Node:
    def __init__(self, value=None):
        # Menyimpan nilai/data node
        self.value = value

        # Pointer ke node berikutnya
        self.next = None

    # Method untuk mengubah object menjadi string
    def __str__(self):
        return str(self.value)


# Membuat class LinkedList
class LinkedList:
    def __init__(self):
        # Node pertama
        self.head = None

        # Node terakhir
        self.tail = None

    # Agar LinkedList bisa di-loop menggunakan for
    def __iter__(self):
        curNode = self.head

        # Loop selama masih ada node
        while curNode:
            yield curNode
            curNode = curNode.next

# Membuat class Queue menggunakan LinkedList
class Queue:
    def __init__(self):
        # Queue menggunakan LinkedList
        self.linkedList = LinkedList()

    # Menampilkan isi queue
    def __str__(self):
        values = [str(x) for x in self.linkedList]
        return ' '.join(values)

    # Menambahkan data ke belakang queue
    def enqueue(self, value):
        newNode = Node(value)

        # Jika queue kosong
        if self.linkedList.head == None:
            self.linkedList.head = newNode
            self.linkedList.tail = newNode

        # Jika queue sudah memiliki data
        else:
            self.linkedList.tail.next = newNode
            self.linkedList.tail = newNode

    # Mengecek apakah queue kosong
    def isEmpty(self):
        if self.linkedList.head == None:
            return True
        else:
            return False

    # Menghapus data paling depan (FIFO)
    def dequeue(self):

        # Jika queue kosong
        if self.isEmpty():
            return "There is not any node in the Queue"

        else:
            tempNode = self.linkedList.head

            # Jika hanya ada 1 node
            if self.linkedList.head == self.linkedList.tail:
                self.linkedList.head = None
                self.linkedList.tail = None

            # Jika ada lebih dari 1 node
            else:
                self.linkedList.head = self.linkedList.head.next

            return tempNode

    # Melihat data paling depan tanpa menghapus
    def peek(self):

        # Jika queue kosong
        if self.isEmpty():
            return "There is not any node in the Queue"

        else:
            return self.linkedList.head

    # Menghapus seluruh isi queue
    def delete(self):
        self.linkedList.head = None
        self.linkedList.tail = None

# Membuat object Queue
custQueue = Queue()

# Menambahkan data ke queue
custQueue.enqueue(1)
custQueue.enqueue(2)
custQueue.enqueue(3)

# Menampilkan isi queue
print(custQueue)

# Menampilkan data paling depan
print(custQueue.peek())

# Queue tetap sama karena peek tidak menghapus data
print(custQueue)

"""---

### QueueNoSize.py `⤵`
"""

# Membuat class Queue
class Queue:

    # Constructor untuk membuat queue kosong
    def __init__(self):
        self.items = []

    # Menampilkan isi queue menjadi string
    def __str__(self):
        values = [str(x) for x in self.items]
        return ' '.join(values)

    # Mengecek apakah queue kosong
    def isEmpty(self):
        if self.items == []:
            return True
        else:
            return False

    # Menambahkan data ke belakang queue
    def enqueue(self, value):
        self.items.append(value)
        return "The element is inserted at the end of Queue"

    # Menghapus data paling depan queue (FIFO)
    def dequeue(self):

        # Jika queue kosong
        if self.isEmpty():
            return "The is not any element in the Queue"

        # Menghapus elemen index pertama
        else:
            return self.items.pop(0)

    # Melihat data paling depan tanpa menghapus
    def peek(self):

        # Jika queue kosong
        if self.isEmpty():
            return "The is not any element in the Queue"

        # Mengembalikan elemen pertama
        else:
            return self.items[0]

    # Menghapus seluruh isi queue
    def delete(self):
        self.items = None

# Membuat object Queue
customQueue = Queue()

# Menambahkan data ke queue
customQueue.enqueue(1)
customQueue.enqueue(2)
customQueue.enqueue(3)

# Menampilkan data paling depan queue
print(customQueue.peek())

# Menghapus seluruh isi queue
customQueue.delete()

"""---

### Stack.py `⤵`
"""

# Membuat class MultiStack
# Class ini digunakan untuk membuat 3 stack dalam 1 array
class MultiStack:

    # Constructor
    def __init__(self, stacksize):

        # Jumlah stack yang digunakan
        self.numstacks = 3

        # Membuat array utama
        # ukuran array = ukuran stack × jumlah stack
        self.array = [0] * (stacksize * self.numstacks)

        # Menyimpan jumlah elemen tiap stack
        self.sizes = [0] * self.numstacks

        # Kapasitas maksimal tiap stack
        self.stacksize = stacksize

        # Debug data
        # print(self.array)
        # print(self.sizes)

    # Menambahkan data ke stack tertentu
    def Push(self, item, stacknum):

        # Mengecek apakah stack penuh
        if self.IsFull(stacknum):
            raise Exception('Stack is full')

        # Menambah ukuran stack
        self.sizes[stacknum] += 1

        # Menyimpan item pada index teratas
        self.array[self.IndexOfTop(stacknum)] = item

    # Menghapus data paling atas stack
    def Pop(self, stacknum):

        # Mengecek apakah stack kosong
        if self.IsEmpty(stacknum):
            raise Exception('Stack is empty')

        # Mengambil nilai paling atas
        value = self.array[self.IndexOfTop(stacknum)]

        # Menghapus nilai dari array
        self.array[self.IndexOfTop(stacknum)] = 0

        # Mengurangi ukuran stack
        self.sizes[stacknum] -= 1

        # Mengembalikan nilai yang dihapus
        return value

    # Melihat data paling atas tanpa menghapus
    def Peek(self, stacknum):

        # Mengecek apakah stack kosong
        if self.IsEmpty(stacknum):
            raise Exception('Stack is empty')

        # Mengembalikan nilai paling atas
        return self.array[self.IndexOfTop(stacknum)]

    # Mengecek apakah stack kosong
    def IsEmpty(self, stacknum):
        return self.sizes[stacknum] == 0

    # Mengecek apakah stack penuh
    def IsFull(self, stacknum):
        return self.sizes[stacknum] == self.stacksize

    # Menentukan index paling atas stack
    def IndexOfTop(self, stacknum):

        # Menentukan posisi awal stack
        offset = stacknum * self.stacksize

        # Menghitung index top
        return offset + self.sizes[stacknum] - 1

# Membuat object MultiStack
# Setiap stack hanya bisa menampung 1 data
stack = MultiStack(1)

"""---

### MultiprocessingQueue.py `⤵`
"""

# Mengimpor Queue dari module multiprocessing
# Queue digunakan untuk membuat antrian FIFO
# FIFO = First In First Out
from multiprocessing import Queue

# Membuat queue dengan kapasitas maksimal 3 data
customQueue = Queue(maxsize=3)

# Menambahkan data ke queue
customQueue.put(1)

# Mengambil data pertama dari queue
# Karena FIFO, data yang pertama masuk akan pertama keluar
print(customQueue.get())

"""---

### QueueModule.py `⤵`
"""

# Mengimpor module queue dengan nama alias q
import queue as q

# Membuat queue dengan kapasitas maksimal 3 data
customQueue = q.Queue(maxsize=3)

# Mengecek apakah queue kosong
# Akan menghasilkan True karena belum ada data
print(customQueue.empty())

# Menambahkan data ke queue
customQueue.put(1)
customQueue.put(2)
customQueue.put(3)

# Mengecek apakah queue penuh
# Akan menghasilkan True karena kapasitas sudah penuh
print(customQueue.full())

# Mengambil data pertama dari queue
# Queue menggunakan sistem FIFO
# Data pertama yang masuk akan keluar lebih dulu
print(customQueue.get())

# Menampilkan jumlah data yang tersisa di queue
print(customQueue.qsize())

"""---

### QueueWithCapacity.py `⤵`
"""

# Membuat class Queue menggunakan Circular Queue
class Queue:

    # Constructor
    def __init__(self, maxSize):
        # Membuat list dengan isi awal None
        self.items = maxSize * [None]
        # Menyimpan kapasitas maksimal queue
        self.maxSize = maxSize
        # Pointer elemen pertama
        self.start = -1
        # Pointer elemen terakhir
        self.top = -1

    # Menampilkan isi queue
    def __str__(self):
        values = [str(x) for x in self.items]
        return ' '.join(values)

    # Mengecek apakah queue penuh
    def isFull(self):
        # Kondisi circular queue penuh
        if self.top + 1 == self.start:
            return True
        # Kondisi saat top di akhir list dan start di awal
        elif self.start == 0 and self.top + 1 == self.maxSize:
            return True
        else:
            return False

    # Mengecek apakah queue kosong
    def isEmpty(self):
        if self.top == -1:
            return True
        else:
            return False

    # Menambahkan data ke queue
    def enqueue(self, value):
        # Jika queue penuh
        if self.isFull():
            return "The queue is full"
        else:
            # Jika top sudah di index terakhir
            # kembali ke index awal
            if self.top + 1 == self.maxSize:
                self.top = 0
            else:
                # Geser top ke kanan
                self.top += 1
                # Jika queue sebelumnya kosong
                if self.start == -1:
                    self.start = 0
            # Menyimpan data ke queue
            self.items[self.top] = value
            return "The element is inserted at the end of Queue"

    # Menghapus data paling depan queue
    def dequeue(self):
        # Jika queue kosong
        if self.isEmpty():
            return "There is not any element in the Queue"
        else:
            # Mengambil elemen pertama
            firstElement = self.items[self.start]
            # Menyimpan posisi start lama
            start = self.start
            # Jika hanya ada 1 elemen
            if self.start == self.top:
                self.start = -1
                self.top = -1
            # Jika start berada di akhir list
            elif self.start + 1 == self.maxSize:
                self.start = 0
            else:
                # Geser start ke kanan
                self.start += 1
            # Menghapus data lama
            self.items[start] = None
            # Mengembalikan data yang dihapus
            return firstElement

    # Melihat elemen paling depan
    def peek(self):
        # Jika queue kosong
        if self.isEmpty():
            return "There is not any element in the Queue"
        else:
            return self.items[self.start]

    # Menghapus seluruh isi queue
    def delete(self):
        # Mengisi ulang queue dengan None
        self.items = self.maxSize * [None]
        # Reset pointer
        self.top = -1
        self.start = -1

# Membuat object Queue dengan kapasitas 3
customQueue = Queue(3)
# Menambahkan data ke queue
customQueue.enqueue(1)
customQueue.enqueue(2)
customQueue.enqueue(3)
# Menghapus seluruh isi queue
customQueue.delete()
# Menampilkan isi queue
print(customQueue)

"""---

### StackLinkedList.py `⤵`
"""

# Membuat class Node
# Node digunakan untuk menyimpan data dan alamat node berikutnya
class Node:
    # Constructor Node
    def __init__(self, value = None):
        # Menyimpan nilai/data
        self.value = value
        # Pointer ke node berikutnya
        self.next = None


# Membuat class LinkedList
class LinkedList:
    # Constructor LinkedList
    def __init__(self):
        # Node pertama
        self.head = None

    # Agar LinkedList bisa di-loop menggunakan for
    def __iter__(self):
        curNode = self.head
        # Loop selama node masih ada
        while curNode:
            yield curNode
            curNode = curNode.next


# Membuat class Stack menggunakan LinkedList
class Stack:
    # Constructor Stack
    def __init__(self):
        # Membuat object LinkedList
        self.LinkedList = LinkedList()

    # Menampilkan isi stack
    def __str__(self):
        values = [str(x.value) for x in self.LinkedList]
        return '\n'.join(values)

    # Mengecek apakah stack kosong
    def isEmpty(self):
        if self.LinkedList.head == None:
            return True
        else:
            return False

    # Menambahkan data ke atas stack
    def push(self, value):
        # Membuat node baru
        node = Node(value)
        # Node baru menunjuk ke head lama
        node.next = self.LinkedList.head
        # Memindahkan head ke node baru
        self.LinkedList.head = node

    # Menghapus data paling atas stack
    def pop(self):
        # Jika stack kosong
        if self.isEmpty():
            return "There is not any element in the stack"
        else:
            # Mengambil nilai head
            nodeValue = self.LinkedList.head.value
            # Memindahkan head ke node berikutnya
            self.LinkedList.head = self.LinkedList.head.next
            # Mengembalikan nilai yang dihapus
            return nodeValue

    # Melihat data paling atas tanpa menghapus
    def peek(self):
        # Jika stack kosong
        if self.isEmpty():
            return "There is not any element in the stack"
        else:
            # Mengambil nilai head
            nodeValue = self.LinkedList.head.value
            return nodeValue

    # Menghapus seluruh isi stack
    def delete(self):
        self.LinkedList.head = None

# Membuat object Stack
customStack = Stack()
# Menambahkan data ke stack
customStack.push(1)
customStack.push(2)
customStack.push(3)
# Menampilkan data paling atas stack
print(customStack.peek())

"""---

### Q1_Stack.py `⤵`
"""

# Menggunakan satu list untuk membuat 3 stack sekaligus

class MultiStack:
    # Constructor
    def __init__(self, stacksize):
        # Jumlah stack
        self.numberstacks = 3
        # Membuat list utama
        # ukuran = ukuran stack × jumlah stack
        self.custList = [0] * (stacksize * self.numberstacks)
        # Menyimpan jumlah elemen tiap stack
        self.sizes = [0] * self.numberstacks
        # Kapasitas maksimal tiap stack
        self.stacksize = stacksize

    # Mengecek apakah stack penuh
    def isFull(self, stacknum):
        if self.sizes[stacknum] == self.stacksize:
            return True
        else:
            return False

    # Mengecek apakah stack kosong
    def isEmpty(self, stacknum):
        if self.sizes[stacknum] == 0:
            return True
        else:
            return False

    # Menentukan posisi index paling atas stack
    def indexOfTop(self, stacknum):
        # Posisi awal stack
        offset = stacknum * self.stacksize
        # Menghitung index top
        return offset + self.sizes[stacknum] - 1

    # Menambahkan data ke stack tertentu
    def push(self, item, stacknum):
        # Jika stack penuh
        if self.isFull(stacknum):
            return "The stack is full"
        else:
            # Menambah jumlah elemen stack
            self.sizes[stacknum] += 1
            # Menyimpan item pada posisi top
            self.custList[self.indexOfTop(stacknum)] = item

    # Menghapus data paling atas stack
    def pop(self, stacknum):
        # Jika stack kosong
        if self.isEmpty(stacknum):
            return "The stack is empty"
        else:
            # Mengambil nilai top
            value = self.custList[self.indexOfTop(stacknum)]
            # Menghapus nilai dari list
            self.custList[self.indexOfTop(stacknum)] = 0
            # Mengurangi ukuran stack
            self.sizes[stacknum] -= 1
            # Mengembalikan nilai yang dihapus
            return value

    # Melihat nilai paling atas tanpa menghapus
    def peek(self, stacknum):
        # Jika stack kosong
        if self.isEmpty(stacknum):
            return "The stack is empty"
        else:
            # Mengambil nilai top
            value = self.custList[self.indexOfTop(stacknum)]
            return value

# Membuat object MultiStack
# Setiap stack memiliki kapasitas 6
customStack = MultiStack(6)
# Mengecek apakah stack ke-0 penuh
print(customStack.isFull(0))
# Mengecek apakah stack ke-1 kosong
print(customStack.isEmpty(1))
# Menambahkan data ke stack ke-0
customStack.push(1, 0)
customStack.push(2, 0)
# Menambahkan data ke stack ke-2
customStack.push(3, 2)
# Menghapus data paling atas dari stack ke-0
print(customStack.pop(0))

"""---

### Q2_Stack.py `⤵`
"""

# Membuat Stack dengan fitur mencari nilai minimum

# Membuat class Node
class Node():
    # Constructor Node
    def __init__(self, value=None, next=None):
        # Menyimpan nilai node
        self.value = value
        # Pointer ke node berikutnya
        self.next = next

    # Mengubah node menjadi string
    def __str__(self):
        string = str(self.value)
        # Jika ada node berikutnya
        if self.next:
            string += ',' + str(self.next)
        return string

# Membuat class Stack
class Stack():
    # Constructor Stack
    def __init__(self):
        # Node paling atas stack
        self.top = None
        # Menyimpan node minimum
        self.minNode = None

    # Mengambil nilai minimum dalam stack
    def min(self):
        # Jika stack kosong
        if not self.minNode:
            return None
        # Mengembalikan nilai minimum
        return self.minNode.value

    # Menambahkan data ke stack
    def push(self, item):
        # Jika sudah ada minNode
        # dan nilai minimum lebih kecil dari item baru
        if self.minNode and (self.minNode.value < item):
            # Simpan nilai minimum sebelumnya
            self.minNode = Node(
                value=self.minNode.value,
                next=self.minNode
            )
        else:
            # Jika item baru lebih kecil
            # jadikan sebagai minimum baru
            self.minNode = Node(
                value=item,
                next=self.minNode
            )
        # Menambahkan item ke top stack
        self.top = Node(value=item, next=self.top)

    # Menghapus data paling atas stack
    def pop(self):
        # Jika stack kosong
        if not self.top:
            return None
        # Memindahkan minNode ke berikutnya
        self.minNode = self.minNode.next
        # Mengambil nilai top
        item = self.top.value
        # Memindahkan top ke node berikutnya
        self.top = self.top.next
        # Mengembalikan nilai yang dihapus
        return item

# Membuat object Stack
customStack = Stack()
# Menambahkan data ke stack
customStack.push(5)
# Menampilkan nilai minimum
print(customStack.min())
# Menambahkan data baru
customStack.push(6)
# Nilai minimum tetap 5
print(customStack.min())
# Menambahkan data lebih kecil
customStack.push(3)
# Nilai minimum berubah menjadi 3
print(customStack.min())
# Menghapus data paling atas (3)
customStack.pop()
# Nilai minimum kembali menjadi 5
print(customStack.min())

"""---

### Q3_StackPlates.py `⤵`
"""

# Membuat Stack of Plates
# Konsep ini membagi stack menjadi beberapa stack kecil
# jika kapasitas stack utama sudah penuh

class PlateStack():
    # Constructor
    def __init__(self, capacity):
        # Kapasitas maksimal tiap stack
        self.capacity = capacity
        # Menyimpan semua stack
        self.stacks = []

    # Menampilkan isi stack
    def __str__(self):
        return self.stacks

    # Menambahkan data ke stack
    def push(self, item):
        # Jika masih ada stack
        # dan stack terakhir belum penuh
        if len(self.stacks) > 0 and (len(self.stacks[-1])) < self.capacity:
            # Tambahkan item ke stack terakhir
            self.stacks[-1].append(item)
        else:
            # Jika penuh, buat stack baru
            self.stacks.append([item])

    # Menghapus data dari stack terakhir
    def pop(self):
        # Menghapus stack kosong di akhir
        while len(self.stacks) and len(self.stacks[-1]) == 0:
            self.stacks.pop()
        # Jika semua stack kosong
        if len(self.stacks) == 0:
            return None
        else:
            # Menghapus item paling atas
            return self.stacks[-1].pop()

    # Menghapus data dari stack tertentu
    def pop_at(self, stackNumber):
        # Jika stack masih memiliki data
        if len(self.stacks[stackNumber]) > 0:
            # Menghapus item paling atas
            return self.stacks[stackNumber].pop()
        else:
            return None

# Membuat object PlateStack
# Setiap stack hanya menampung 2 item
customStack = PlateStack(2)
# Menambahkan data ke stack
customStack.push(1)
customStack.push(2)
# Karena stack pertama penuh
# maka akan dibuat stack baru
customStack.push(3)
customStack.push(4)

"""---

### Q4_QueueStack.py `⤵`
"""

# Mengimplementasikan Queue menggunakan dua Stack

# Membuat class Stack
class Stack():
    # Constructor
    def __init__(self):
        # List untuk menyimpan data stack
        self.list = []

    # Mengembalikan jumlah data dalam stack
    def __len__(self):
        return len(self.list)

    # Menambahkan data ke atas stack
    def push(self, item):
        self.list.append(item)

    # Menghapus data paling atas stack
    def pop(self):
        # Jika stack kosong
        if len(self.list) == 0:
            return None
        # Menghapus data terakhir
        return self.list.pop()


# Membuat Queue menggunakan dua stack
class QueueviaStack():
    # Constructor
    def __init__(self):
        # Stack untuk data masuk
        self.inStack = Stack()
        # Stack untuk membalik urutan data
        self.outStack = Stack()

    # Menambahkan data ke queue
    def enqueue(self, item):
        self.inStack.push(item)

    # Menghapus data paling depan queue
    def dequeue(self):
        # Memindahkan semua data dari inStack ke outStack
        # agar urutan menjadi FIFO
        while len(self.inStack):
            self.outStack.push(self.inStack.pop())
        # Mengambil data paling depan
        result = self.outStack.pop()
        # Mengembalikan data ke inStack
        while len(self.outStack):
            self.inStack.push(self.outStack.pop())
        # Mengembalikan hasil dequeue
        return result

# Membuat object Queue
customQueue = QueueviaStack()
# Menambahkan data ke queue
customQueue.enqueue(1)
customQueue.enqueue(2)
customQueue.enqueue(3)
# Menghapus data pertama
print(customQueue.dequeue())
# Menambahkan data baru
customQueue.enqueue(4)
# Menghapus data pertama berikutnya
print(customQueue.dequeue())

"""---

### Q5_AnimalShelter.py `⤵`
"""

# Mengimplementasikan queue untuk tempat penampungan hewan
# Queue ini memisahkan antrian kucing dan anjing

class AnimalShelter():
    # Constructor
    def __init__(self):
        # List untuk menyimpan kucing
        self.cats = []
        # List untuk menyimpan anjing
        self.dogs = []

    # Menambahkan hewan ke antrian
    def enqueue(self, animal, type):
        # Jika hewan adalah kucing
        if type == 'Cat':
            self.cats.append(animal)
        # Jika hewan adalah anjing
        else:
            self.dogs.append(animal)

    # Mengambil kucing pertama dari antrian
    def dequeueCat(self):
        # Jika tidak ada kucing
        if len(self.cats) == 0:
            return None
        else:
            # Menghapus kucing pertama
            cat = self.cats.pop(0)
            return cat

    # Mengambil anjing pertama dari antrian
    def dequeueDog(self):
        # Jika tidak ada anjing
        if len(self.dogs) == 0:
            return None
        else:
            # Menghapus anjing pertama
            dog = self.dogs.pop(0)
            return dog

    # Mengambil hewan pertama secara umum
    def dequeueAny(self):

        # Jika tidak ada kucing
        if len(self.cats) == 0:
            result = self.dogs.pop(0)
        # Jika ada kucing
        else:
            result = self.cats.pop(0)
        return result

# Membuat object AnimalShelter
customQueue = AnimalShelter()
# Menambahkan hewan ke antrian
customQueue.enqueue('Cat1', 'Cat')
customQueue.enqueue('Cat2', 'Cat')
customQueue.enqueue('Dog1', 'Dog')
customQueue.enqueue('Cat3', 'Cat')
customQueue.enqueue('Dog2', 'Dog')
# Mengambil hewan pertama dari antrian
print(customQueue.dequeueAny())

"""---

### Q6_SortStack.py `⤵`
"""

# Mengurutkan stack dengan nilai terkecil berada di atas
# Menggunakan hanya satu stack sementara

# Function untuk mengurutkan stack
def sort_stack(stack):

    # Mengambil dua data pertama dari stack
    previous = stack.pop()
    current = stack.pop()
    # Stack sementara
    temp = Stack()

    # Proses pengurutan awal
    while current:
        # Jika previous lebih kecil dari current
        if previous < current:
            # Simpan previous ke temp
            temp.push(previous)
            # Update previous
            previous = current
            # Ambil data berikutnya
            current = stack.pop()
        else:
            # Simpan current ke temp
            temp.push(current)
            # Ambil data berikutnya
            current = stack.pop()
        # Jika sudah akhir stack
        if current == None and previous:
            temp.push(previous)

    # Menandai apakah stack sudah terurut
    sorted = True

    # Mengambil data dari temp
    previous = temp.pop()
    current = temp.pop()

    # Mengembalikan data ke stack utama
    while current:
        # Jika previous lebih besar dari current
        if previous > current:
            # Masukkan previous ke stack utama
            stack.push(previous)
            # Update previous
            previous = current
            # Ambil data berikutnya
            current = temp.pop()
        else:
            # Masukkan current ke stack utama
            stack.push(current)
            # Ambil data berikutnya
            current = temp.pop()
            # Menandakan stack belum sepenuhnya terurut
            sorted = False
        # Jika sudah akhir temp stack
        if current == None and previous:
            stack.push(previous)
    # Jika sudah terurut
    if sorted:
        return stack
    # Jika belum terurut, ulangi sorting
    else:
        return sort_stack(stack)


# Membuat class Stack
class Stack():
    # Constructor
    def __init__(self):
        # Node paling atas
        self.top = None

    # Menampilkan isi stack
    def __str__(self):
        return str(self.top)

    # Menambahkan data ke stack
    def push(self, item):
        self.top = current(item, self.top)

    # Menghapus data paling atas stack
    def pop(self):
        # Jika stack kosong
        if not self.top:
            return None
        # Mengambil node teratas
        item = self.top
        # Memindahkan top ke node berikutnya
        self.top = self.top.next
        # Mengembalikan data
        return item.data


# Membuat class node
class current():

    # Constructor node
    def __init__(self, data=None, next=None):
        # Menyimpan data
        self.data = data
        # Pointer ke node berikutnya
        self.next = next

    # Menampilkan node sebagai string
    def __str__(self):
        return str(self and self.data) + ',' + str(self and self.next)
# Module untuk testing
import unittest

# Membuat class testing
class Test(unittest.TestCase):
    # Function test sorting stack
    def test_sort_stack(self):
        # Test stack kosong
        self.assertEqual(str(sort_stack(Stack())), "None")

        # Membuat object stack
        stack = Stack()

        # Menambahkan data ke stack
        stack.push(10)
        stack.push(30)
        stack.push(70)
        stack.push(40)
        stack.push(80)
        stack.push(20)
        stack.push(90)
        stack.push(50)
        stack.push(60)

        # Kondisi sebelum sorting
        self.assertEqual(
            str(stack),
            "60,50,90,20,80,40,70,30,10,None"
        )
        # Kondisi setelah sorting
        self.assertEqual(
            str(sort_stack(stack)),
            "10,20,30,40,50,60,70,80,90,None"
        )

# Menjalankan unit test
unittest.main()